### ISSUE TITLE
Reproducing the system performance

### ISSUE THREAD

**Issue by vhientran** [ivan-bilan/tac-self-attention#5] opened 2019-12-10 02:37 UTC
Dear @ivan-bilan ,
I am sorry for disturbing you, but I am trying to reproduce your best performance on a single model as in your paper (P=64.4, R=68.6, F1=66.5). However, I cannot achieve this result.
I set up the environment as you guided: (Python 3.6.8, Pytorch 1.2, CuDNN 7602, CUDA 10.0.130). Then, I train the final model:

python runner.py --data_dir dataset/tacred --vocab_dir dataset/vocab --id 00 
--info "Position-aware attention model with self-attention encoder"

, and evaluate on both the best_model.pt and checkpoint_epoch_60.pt, using:
python eval.py --model_dir saved_models/00
python eval.py --model_dir saved_models/00 --model checkpoint_epoch_60.pt

The performances are (Precision (micro): 59.994%, Recall (micro): 64.541%, F1 (micro): 62.185%), and (Precision (micro): 57.848%, Recall (micro): 65.955%, F1 (micro): 61.636%), respectively. I would like to send you the file logs.txt and config.json in the training phase. Please help me to resolve this problem since I don't know why the difference is large.
[logs.txt](https://github.com/ivan-bilan/tac-self-attention/files/3942748/logs.txt)
[config.txt](https://github.com/ivan-bilan/tac-self-attention/files/3942752/config.txt)

Thank you very much for your help!

**Comment by vhientran** [comment] 2019-12-13 14:16
Could you give me any advice on resolving this problem?

**Comment by ivan-bilan** [comment] 2019-12-13 14:39
Hi, @hientrannaist. I also see the degraded performance with newer PyTorch versions. When the pre-print on ArXiv was published, PyTorch 0.4.1 was used to evaluate the results and that is what we were getting. I think due to changes in PyTorch the results have also been affected. Also, as much as I've tried to make the computation deterministic I still often get different results from one run to the other.

Currently, I am not able to work on this project, but you are welcome to contribute with a Pull Request if you happen to find the cause of degraded performance. 

Please, note that this project is marked as _Work In Progress_ and there is only a pre-print available. The approach has not been published in any conference since there is still a long TODO list attached to it.

**Comment by vhientran** [comment] 2019-12-14 01:06
HI, @ivan-bilan , Thank you for your advice. I will try with PyTorch 0.4.1. Also, I will provide some information whether I find out the cause of degraded performance. Thank you for your time. :)

**Closed as completed** 2019-12-14 01:34 UTC
